### ISSUE TITLE
Hello,is it possible to perform  cityscape to foggy cityscape adaptation? if so can you add the instructions and config file please?

### ISSUE THREAD

**Issue by tyunit** [XuYunqiu/H2FA_R-CNN#2]

**Comment by XuYunqiu** [comment]
Hi, thanks for the interest in this work. H<sup>2</sup>FA R-CNN can perform `CityScapes -> Foggy CityScapes` adaptation.
However, since Foggy Cityscapes is not a commonly used dataset in CDWSOD, I did not add it to this repository.
The support for `CityScapes -> Foggy CityScapes` adaptation will be added in the next update in the near future.
