### ISSUE TITLE
It's that normal for automatically stop training？

### ISSUE THREAD

**Issue by 1184125805** [XuYunqiu/H2FA_R-CNN#5]
![image](https://user-images.githubusercontent.com/38450078/203935137-8851b779-329e-4854-a7a1-5daaed124ee4.png)
The training program stopped

**Comment by 1184125805** [comment]
![image](https://user-images.githubusercontent.com/38450078/203936254-50405d01-8c2d-42e0-b2c5-4c3d3b25cdd5.png)

**Comment by XuYunqiu** [comment]
As shown in the log information, your model is successfully trained. 
The training process is finished and stopped, because you set the max training iterations (i.e., `MAX_ITER`  in config file) to 36k.

However, I find the performance you reported is much lower than expected.  I think the issue probably exists in your config file.
With two GPUs, the max training iterations for Clipart<sub>test</sub> should be 24k instead of 36k you used before. 
In addition, if you want to train models with a single GPU, you need to adjust some hyper-parameters (`IMS_PER_BATCH` and `BASE_LR` should be halved, and `STEPS` , `MAX_ITER` and `WARMUP_ITERS` should be doubled).

**Comment by XuYunqiu** [comment]
I'm closing this issue, but let me know if you have further questions.
