### ISSUE TITLE
How to embed it to my own model?

### ISSUE THREAD

**Issue by zml110120** [XuYunqiu/H2FA_R-CNN#6]
## ❓ How to embed it to my own model

I mean, how to embed H2FA as a module into our own model (something else, not object detection). I want to get category information and bbox information, not metrics. What should I do?

**Comment by XuYunqiu** [comment]
Hi, our H<sup>2</sup>FA R-CNN is tailored for the object detection task.
I'm afraid you cannot use the two instance-level alignments without bbox annotations of the source domain.
Still, you can use the two image-level alignments, where the image-level class-wise alignment can only be utilized when image-level annotations of both domains are available. 

I'm not quite sure what you mean by ‘I want to get category information and bbox information, not metrics.’
Do you only want to get the inference results, rather than the final metrics?

**Comment by zml110120** [comment]
Yes! I want to get the inference results, rather than the final metrics.

**Comment by XuYunqiu** [comment]
Before metric evaluation, the inference results have been written to `./datasets/results/VOC2007/Main/` in a VOC style. You can check the detection predictions in this folder.

If you want to extract and save the predictions in your own logic, you can reimplement the following code:
https://github.com/XuYunqiu/H2FA_R-CNN/blob/6b76bd797049a9a129ae67e129d31b27e89f0445/detectron2/evaluation/cdod_evaluation.py#L69-L106

**Comment by XuYunqiu** [comment]
I'm closing this issue, but let me know if you have further questions.
